import os

os.system(
    "python ./AI_SFC_2_train_EnhancedResUnet.py "
    "--gpuID 0 "
    "--training_data_disk G "
    "--models_disk G "
    "--stride 8 8 "
    "--loss_used 5 "
    "--kernel_size 11 "
    "--BridgeNet_used 5 "
    "--training_number 10000 "
    "--epochs 3 "
    "--lr 0.0001 "
    "--kernels_all 16 32 64 128 256 512 "
    "--batch_size 16 "
    "--patch_rows 992 "
    "--patch_cols 576 "
    "--conv2act_repeat 2 "
    "--save_every 1 "
    "--res_case 0 "
    "--res_number 1 "
    "--reproduce 1 "
    # "--plot_show "
    # "--continue_train "
)

for i in range(30):
    os.system(
        "python ./AI_SFC_2_train_EnhancedResUnet.py "
        "--gpuID 0 "
        "--training_data_disk G "
        "--models_disk G "
        "--stride 8 8 "
        "--loss_used 5 "
        "--kernel_size 11 "
        "--BridgeNet_used 5 "
        "--training_number 10000 "
        "--epochs 3 "
        "--lr 0.0001 "
        "--kernels_all 16 32 64 128 256 512 "
        "--batch_size 16 "
        "--patch_rows 992 "
        "--patch_cols 576 "
        "--conv2act_repeat 2 "
        "--save_every 1 "
        "--res_case 3 "
        "--res_number 1 "
        "--reproduce " + str((i + 1)) + " "
        # "--plot_show "
        # "--continue_train "
    )
